name: Build & Publish
on:
  push:
    tags:        
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=tag_version::${GITHUB_REF/refs\/tags\//}

    - name: Publish release
      shell: bash
      run: |
          chmod +x ./.github/scripts/git-release.sh
          ./.github/scripts/git-release.sh
      env: 
        token: ${{ secrets.REPOREADING_TOKEN }}
        tagversion: ${{ steps.get_version.outputs.tag_version }}


